modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"
issueTrackerURL="https://github.com/CreateTechified/TechifiedExtras/issues/"
clientSideOnly=false

[[mods]]
modId="techifiedextras"
version="1.0.0"
displayName="TechifiedExtras" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="examplemod.png"
#credits=""
authors="wrldmap, pineapple"
displayTest="MATCH_VERSION"
description='''Stuff that may be merged into TechifiedCore, but is a seperate mod for now. Mainly for testing.'''

[[dependencies.techifiedextras]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.techifiedextras]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1, 1.21)"
ordering="NONE"
side="BOTH"

#[features.techifiedextras]
#openGLVersion="[3.2,)"